### ISSUE TITLE
Simple CRUD API using Spring Boot

### ISSUE THREAD

**Issue by TheInspiredConjurer** [KrishGaur1354/Java-Projects#4]
hi. I want to add a simple REST API for performing CRUD operations on a simple Student Model using Spring Boot and Hibernates.

Please assign me to this as part of Hacktoberfest.

**Comment by KrishGaur1354** [comment]
isn't this really difficult for beginner's to Understand

**Comment by TheInspiredConjurer** [comment]
Well then... if you have any other suggestions, I will gladly take it up.

**Comment by TheInspiredConjurer** [comment]
> isn't this really difficult for beginner's to Understand

Well then... if you have any other suggestions, I will gladly take it up.

**Comment by KrishGaur1354** [comment]
You can create anything simple and easy to Understand currently without using API's

**Comment by TheInspiredConjurer** [comment]
Okay then.
